<?xml version="1.0"?>
<robot name="hockey_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================= -->
  <!-- Arguments -->
  <!-- ========================= -->
  <xacro:arg name="prefix" default=""/>
  <xacro:property name="prefix" value="$(arg prefix)"/>

  <xacro:arg name="ns" default=""/>
  <xacro:property name="ns" value="$(arg ns)"/>


  <!-- ========================= -->
  <!-- Dimensions -->
  <!-- ========================= -->
  <xacro:property name="base_length" value="0.40"/>
  <xacro:property name="base_width"  value="0.30"/>
  <xacro:property name="base_height" value="0.10"/>

  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width"  value="0.02"/>

  <xacro:property name="caster_radius" value="0.03"/>

  <!-- Offsets -->
  <xacro:property name="rear_x"  value="${-base_length/2 + wheel_radius}"/>
  <xacro:property name="front_x" value="${ base_length/2 - caster_radius}"/>
  <xacro:property name="left_y"  value="${ base_width/2}"/>
  <xacro:property name="right_y" value="${-base_width/2}"/>

  <!-- ========================= -->
  <!-- Materials -->
  <!-- ========================= -->
  <material name="Black">
    <color rgba="0.05 0.05 0.05 1.0"/>
  </material>

  <material name="Blue">
    <color rgba="0.1 0.3 0.8 1.0"/>
  </material>

  <material name="White">
    <color rgba="0.95 0.95 0.95 1.0"/>
  </material>

  <material name="Red">
    <color rgba="0.8 0.1 0.1 1.0"/>
  </material>

  <!-- ========================= -->
  <!-- BASE LINK -->
  <!-- ========================= -->
  <link name="${prefix}base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz=" 0 0 0.02" rpy = "0 0 0"/>
      <material name="Blue"/>
    </visual>

    <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <origin xyz=" 0 0 0.02" rpy = "0 0 0"/>
    </collision>

    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.1"/>
    </inertial>
  </link>

  <!-- ========================= -->
  <!-- LEFT WHEEL -->
  <!-- ========================= -->
  <link name="${prefix}left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="-1.5708 0 0"/>
      <material name="Black"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="-1.5708 0 0"/>
    </collision>

    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="${prefix}left_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}left_wheel_link"/>
    <origin xyz="${rear_x} ${left_y} 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ========================= -->
  <!-- RIGHT WHEEL -->
  <!-- ========================= -->
  <link name="${prefix}right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin rpy="-1.5708 0 0"/>
      <material name="Black"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="0 1.5708 0"/>
    </collision>

    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" iyy="0.001" izz="0.001"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="${prefix}right_wheel_joint" type="continuous">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}right_wheel_link"/>
    <origin xyz="${rear_x} ${right_y} 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- ========================= -->
  <!-- FRONT LEFT CASTER -->
  <!-- ========================= -->
  <link name="${prefix}front_left_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="White"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="${prefix}front_left_caster_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}front_left_caster"/>
    <origin xyz="${front_x} ${left_y} ${-base_height/2 + caster_radius}"/>
  </joint>

  <!-- ========================= -->
  <!-- FRONT RIGHT CASTER -->
  <!-- ========================= -->
  <link name="${prefix}front_right_caster">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <material name="White"/>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${caster_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>0.1</mu>
            <mu2>0.1</mu2>
          </ode>
        </friction>
      </surface>
    </collision>

    <inertial>
      <mass value="0.1"/>
      <inertia ixx="0.0001" iyy="0.0001" izz="0.0001"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="${prefix}front_right_caster_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}front_right_caster"/>
    <origin xyz="${front_x} ${right_y} ${-base_height/2 + caster_radius}"/>
  </joint>

  <!-- ========================= -->
  <!-- LIDAR -->
  <!-- ========================= -->
  <link name="${prefix}lidar_link">
    <visual>
      <geometry>
        <cylinder radius="0.035" length="0.01"/>
      </geometry>
      <origin rpy="0 0 0"/>
      <material name="Red"/>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="0.035" length="0.01"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1e-6"/>
      <inertia ixx="1e-6" iyy="1e-6" izz="1e-6"     
               ixy="0.0" ixz="0.0" iyz="0.0"/>   <!--0.0001-->
    </inertial>
  </link>

  <joint name="${prefix}lidar_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}lidar_link"/>
    <origin xyz="0 0 ${base_height/2 + 0.03}"/> <!--${base_height/2 + 0.02}-->
  </joint>

  <gazebo reference="${prefix}lidar_link">
    <sensor name="lidar" type="gpu_lidar" >
      <update_rate>10</update_rate>
      <topic>/${ns}/scan</topic>

      <frame_id>${prefix}lidar_link</frame_id>
      
      <lidar>
        <scan>
          <horizontal>
            <samples>720</samples>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.01</min>
          <max>8.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <mean>0.0</mean>
          <stddev>0.001</stddev>
        </noise>
      </lidar>
      <always_on>1</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

  <!-- ========================= -->
  <!-- IMU -->
  <!-- ========================= -->
  <link name="${prefix}imu_link">
    <inertial>
      <mass value="0.01"/>
      <inertia ixx="0.00001" iyy="0.00001" izz="0.00001"
               ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
  </link>

  <joint name="${prefix}imu_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}imu_link"/>
    <origin xyz="0 0 0"/>
  </joint>

  <gazebo reference="${prefix}imu_link">
    <sensor type="imu" name="imu">
      <topic>/${ns}/imu</topic>
      <frame_id>${prefix}imu_link</frame_id>
      <update_rate>100</update_rate>
      <always_on>1</always_on>
    </sensor>
  </gazebo>

  <!-- ========================= -->
  <!-- DIFFERENTIAL DRIVE -->
  <!-- ========================= -->
  <gazebo>
    <plugin filename="gz-sim-diff-drive-system"
            name="gz::sim::systems::DiffDrive">
            <render_engine>ogre2</render_engine>

      <left_joint>${prefix}left_wheel_joint</left_joint>
      <right_joint>${prefix}right_wheel_joint</right_joint>

      <wheel_separation>${base_width}</wheel_separation>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <topic>/${ns}/cmd_vel</topic>
      <odom_topic>/${ns}/odom</odom_topic>
      <odom_frame>odom</odom_frame>
      <robot_base_frame>${prefix}base_link</robot_base_frame>
      
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin
      filename="gz-sim-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher">
    </plugin>
  </gazebo>

  <!-- Additional Gazebo physics properties -->
  <gazebo reference="${prefix}base_link">
    <material>Gazebo/Blue</material>
  </gazebo>

  <gazebo reference="${prefix}left_wheel_link">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

  <gazebo reference="${prefix}right_wheel_link">
    <material>Gazebo/Black</material>
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
  </gazebo>

</robot>